/* special keywords for 8051*/ 
DEF(TOK_IDATA, "idata")
DEF(TOK_XDATA, "xdata")
DEF(TOK_CODE, "code")
DEF(TOK_SBIT, "sbit")
DEF(TOK_SFR, "sfr")
DEF(TOK_SFR16, "sfr16")
DEF(TOK_BIT, "bit")
DEF(TOK_INTERRUPT, "interrupt") 

DEF(TOK_VOID, "void")
DEF(TOK_BOOL, "bool")
DEF(TOK_CHAR, "char")
DEF(TOK_SHORT, "short")
DEF(TOK_INT, "int")
DEF(TOK_LONG, "long")
DEF(TOK_FLOAT, "float")
DEF(TOK_DOUBLE, "double")
DEF(TOK_AUTO, "auto")

DEF(TOK_STATIC, "static")
DEF(TOK_CONST, "const")
DEF(TOK_SIGNED, "signed")
DEF(TOK_UNSIGNED, "unsigned")
DEF(TOK_VOLATILE, "volatile")
DEF(TOK_INLINE1, "inline")

DEF(TOK_STRUCT, "struct")
DEF(TOK_UNION, "union")
DEF(TOK_TYPEDEF, "typedef")
DEF(TOK_DEFAULT, "default")
DEF(TOK_ENUM, "enum")
DEF(TOK_SIZEOF, "sizeof")
DEF(TOK_TYPEOF, "typeof")
DEF(TOK_ASM, "asm")

/* keywords */
DEF(TOK_IF, "if")
DEF(TOK_ELSE, "else")
DEF(TOK_SWITCH, "switch")
DEF(TOK_CASE, "case")
DEF(TOK_DO, "do")
DEF(TOK_WHILE, "while")
DEF(TOK_FOR, "for")
DEF(TOK_CONTINUE, "continue")
DEF(TOK_BREAK, "break")
DEF(TOK_RETURN, "return")
DEF(TOK_GOTO, "goto")